@startuml CdU_Generador
left to right direction

actor "Generador" as Generador

package "Generación de Exámenes" {
    usecase "Procesar Solicitud de Generación" as ProcesarGeneracion
    usecase "Generar Fechas de Exámenes" as GenerarFechas
    usecase "Revisar Posibles Conflictos" as RevisarConflictos
    usecase "Aplicar Correcciones Solicitadas" as AplicarCorrecciones
    usecase "Finalizar Asignación de Exámenes" as FinalizarAsignacion
}

Generador --> ProcesarGeneracion
Generador --> GenerarFechas
Generador --> RevisarConflictos
Generador --> AplicarCorrecciones
Generador --> FinalizarAsignacion

ProcesarGeneracion --> GenerarFechas : <<include>>
GenerarFechas --> RevisarConflictos : <<include>>
RevisarConflictos --> FinalizarAsignacion : <<extend>>
AplicarCorrecciones --> GenerarFechas : <<extend>>

@enduml
