@startuml CdU_Profesor
left to right direction

actor Profesor

package "Consultas de Exámenes" {
    usecase "Comunicar Incidencias de Horario" as ComunicarIncidencias
    usecase "Ver Calendario de Exámenes" as VerCalendario
}

usecase "Descargar Calendario de Exámenes" as DescargarCalendario

Profesor --> ComunicarIncidencias
Profesor --> VerCalendario
VerCalendario -[hidden]--> DescargarCalendario

DescargarCalendario ..> VerCalendario : <<extend>>

@enduml
