@startuml

[*] --> PendienteDeAsignar

PendienteDeAsignar --> Asignando : iniciarAsignación()

Asignando --> PendienteDeRevisión : fechasGeneradas()

PendienteDeRevisión --> Asignando : solicitarCorrección()
PendienteDeRevisión --> Finalizado : aprobarAsignación()

Finalizado --> [*]

@enduml
